version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - secure_vault_data:/var/secure_vault/data
    environment:
      - DATABASE_TYPE=postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=secure_vault
      - DATABASE_USER=secure_vault_user
      - DATABASE_PASSWORD=secure_password
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=secure_vault
      - POSTGRES_USER=secure_vault_user
      - POSTGRES_PASSWORD=secure_password

volumes:
  secure_vault_data:
  postgres_data:
